query($after: String, $first: Int) {
    allPoems(after: $after, first: $first) {
        edges {
            node {
                title
                author
                id
            }
        }
    }
}