query($first: Int, $last: Int) {
    allPoems(first: $first, last: $last) {
        totalCount
        edges {
            node {
                title
                author
                id
            }
        }
    }
}