query($poemID: ID!) {
    node(id: $poemID) {
        ...on Poem {
            id
            location
            title
            author
            lines {
                id
                order
                text
                key
                stanzaBreak
            }
        }
    }
}