query($id: ID!) {
    node(id: $id) {
        ...on Poem {
            id
            title
            author
            location
            categories {
                name
            }
            lines {
                id
                order
                text
                key
                stanzaBreak
            }
        }
    }
}