export { default as submitLine } from './submitLine.gql'
export { default as randomPoemID } from './randomPoemID.gql'
export { default as poem } from './poem.gql'
export { default as login } from './login.gql'
export { default as register } from './register.gql'
export { default as inProgress } from './inProgress.gql'
export { default as completed } from './completed.gql'
export { default as resetProgress } from './resetProgress.gql'