query {
    me {
        inProgress {
            edges {
                node {
                    id
                    location
                    title
                    author
                    numLines
                    progress {
                        numCorrect
                    }
                }
            }
        }
    }
}