query {
    poems: poemsInProgress {
        edges {
            node {
                id
                title
                author
                numLines
                progress {
                    numCorrect
                }
            }
        }
    }
}