mutation($location: JSONString!) {
    playPoem(location: $location) {
        poem {
            title
            author
            lines {
                number
                text
                stanzaBreak
            }
            progress {
                lines {
                    answer
                    number
                    correct
                }
                numCorrect
            }
        }
    }
}