mutation($location: String!) {
    playPoem(location: $location) {
        next
        previous
        poem {
            id
            title
            author
            lines {
                id
                order
                numFeet
                text
                stanzaBreak
            }
            progress {
                lines {
                    key
                    value {
                        answer
                        correct
                    }
                }
                numCorrect
            }
        }
    }
}