query($id: ID!) {
    poem: node(id: $id) {
        ... on Poem {
            name
            author
            lines {
                number
                stanza
                text
            }
        }
    }
}