query($id: ID!) {
    poem: node(id: $id) {
        ... on Poem {
            title
            author
            lines {
                edges {
                    node {
                        number
                        text
                    }
                }
            }
        }
    }
}