query($first: Int, $last: Int, $search: String, $categories_In: [String], $orderBy: String) {
    poems(first: $first, last: $last, search: $search, categories_In: $categories_In, orderBy: $orderBy) {
        totalCount
        edges {
            node {
                title
                author
                id
            }
        }
    }
}