query($first: Int, $last: Int, $search: String, $orderBy: String) {
    poems(first: $first, last: $last, search: $search, orderBy: $orderBy) {
        totalCount
        edges {
            node {
                title
                author
                id
            }
        }
    }
}