"Light-weight node definition"
interface Node {
  id: ID!
}

type Line {
  number: Int!
  stanza: Int
  text: String!
}

type Poem implements Node {
  id: ID!
  name: String!
  author: String
  lines: [Line]!
}

type Query {
  node(id: ID!): Node
}

type Mutation {
  randomPoem: Poem!
}
