"Light-weight node definition"
interface Node {
  id: ID!
}

type Line {
  number: Int!
  stanzaBreak: Boolean
  text: String!
}

type Poem implements Node {
  id: ID!
  name: String!
  author: String
  lines: [[Line]]!
}

type Query {
  node(id: ID!): Node
}

input CheckLineInput {
  poemID: ID!
  lineNum: Int!
  answer: String!
}

type CheckLineOutput {
  correct: Boolean!
  hintIndicies: [Int]!
}

type Mutation {
  randomPoem: Poem!
  checkLine(input: CheckLineInput!): CheckLineOutput!
}
